common = {
    "SUCCESS": 200,
    "NO_CONTENT": 204,
    "FORBIDDEN": 403,
    "SUCCESS_CREATED": 201,
    "FAILURE": 400,
    "INVALID_DATA": 400,
    "UNAUTHORIZED": 401,
    "ALREADY_EXISTING": 409,
    "SERVER_ERROR": 500,
    "SUCCESS_CREATED_MSG": "Successfully Created",
    "SUCCESS_MSG": "Success",
    "FAILURE_MSG": "Failure",
    "SERVER_ERROR_MSG": "Internal Server Error",
    "LOGIN_SUCCESS": "Login Success",
    "LOGIN_FAILED": "Invalid Email/Password",
    "UNAUTHORIZED_MSG": "Unauthorized",
    "APP_TOKEN_MISSING": "Provide Application Token",
    "INVALID_EMAIL": "Invalid Email",
    "INVALID_PASSWORD": "Invalid Password",
    "INVALID_PARAM": "Invalid Parameters",
    "NO_CONTENT_MSG": "No Content",
    "ALREADY_EXISTING_MSG": "Already Existing",
    "SUCCESS_ALERT": "success",
    "FAILURE_ALERT": "failure",
    "QUIZ_POINT_HISTORY_IMAGE_URL": "Activity/quiz_history_image.png",
}
