"""Migrate DB local Base

Revision ID: c40a4b0dc2e2
Revises: 2b4bcd1f87d7
Create Date: 2024-01-07 19:00:15.086269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c40a4b0dc2e2'
down_revision: Union[str, None] = '2b4bcd1f87d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
